import * as path from 'path';

/**
 * Saves a TF.js LayersModel to disk in the format expected by the Python tf2onnx converter,
 * and returns the shell commands to complete the conversion to .onnx.
 *
 * ## Full conversion flow
 *
 * **Step 1 (JS)** — Call this function to save the model:
 * ```ts
 * import { DQNAgent } from '@ignitionai/backend-tfjs';
 * import { saveForOnnxExport } from '@ignitionai/backend-onnx';
 *
 * const { modelDir, conversionScript } = await saveForOnnxExport(agent.model, './exports/my_model');
 * console.log(conversionScript); // Print or execute the Python script
 * ```
 *
 * **Step 2 (Python)** — Run the generated script:
 * ```bash
 * pip install tensorflowjs tf2onnx
 * tensorflowjs_converter --input_format=tfjs_layers_model \
 *   ./exports/my_model/model.json ./exports/my_model_savedmodel/
 * python -m tf2onnx.convert \
 *   --saved-model ./exports/my_model_savedmodel \
 *   --output ./exports/my_model.onnx \
 *   --opset 13
 * ```
 *
 * **Step 3 (JS)** — Load with OnnxAgent:
 * ```ts
 * const agent = new OnnxAgent({ modelPath: './exports/my_model.onnx', actionSize: 4 });
 * await agent.load();
 * ```
 *
 * ## Why Python?
 * No maintained npm package performs reliable TF.js → ONNX conversion.
 * The official path is: TF.js JSON → TF SavedModel (via tensorflowjs_converter) → ONNX (via tf2onnx).
 */

export interface ExportResult {
  /** Directory where the TF.js model was saved (model.json + weights.bin) */
  modelDir: string;
  /** Shell script (bash) that converts the saved model to .onnx */
  conversionScript: string;
}

/**
 * Saves a TF.js LayersModel to `outputDir` and returns the Python conversion script.
 *
 * @param model     - A TF.js `tf.LayersModel` (e.g. `dqnAgent.getModel()`)
 * @param outputDir - Directory path where the TF.js model will be saved
 * @param onnxOutputPath - Desired output path for the final .onnx file (default: `<outputDir>.onnx`)
 */
export async function saveForOnnxExport(
  model: { save: (url: string) => Promise<unknown> },
  outputDir: string,
  onnxOutputPath?: string,
): Promise<ExportResult> {
  const resolvedDir = path.resolve(outputDir);
  const savedModelDir = resolvedDir + '_savedmodel';
  const onnxPath = onnxOutputPath ?? resolvedDir + '.onnx';

  await model.save(`file://${resolvedDir}`);

  const conversionScript = generateConversionScript(resolvedDir, savedModelDir, onnxPath);

  return { modelDir: resolvedDir, conversionScript };
}

/**
 * Generates the bash conversion script without saving the model.
 * Useful when you want to preview the commands or use a pre-saved model.
 *
 * @param tfjsModelDir    - Directory containing TF.js model.json
 * @param savedModelDir   - Intermediate TF SavedModel output directory
 * @param onnxOutputPath  - Final .onnx output path
 */
export function generateConversionScript(
  tfjsModelDir: string,
  savedModelDir: string,
  onnxOutputPath: string,
): string {
  return `#!/bin/bash
# IgnitionAI — TF.js to ONNX conversion script
# Generated by @ignitionai/backend-onnx

set -e

echo "📦 Installing Python dependencies..."
pip install --quiet tensorflowjs tf2onnx

echo "🔄 Step 1: TF.js → TF SavedModel"
tensorflowjs_converter \\
  --input_format=tfjs_layers_model \\
  "${tfjsModelDir}/model.json" \\
  "${savedModelDir}/"

echo "🔄 Step 2: TF SavedModel → ONNX"
python -m tf2onnx.convert \\
  --saved-model "${savedModelDir}" \\
  --output "${onnxOutputPath}" \\
  --opset 13

echo "✅ Done! ONNX model saved to: ${onnxOutputPath}"
echo ""
echo "Load with OnnxAgent:"
echo "  const agent = new OnnxAgent({ modelPath: '${onnxOutputPath}', actionSize: <N> });"
echo "  await agent.load();"
`;
}
